---
name: "workflow"

on:
  push:
    branches:
      - master
      - branch1

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
  
      - name: "Date"
        run: date
        
      - name: "OS"
        run : cat /etc/issue

      - name: "user"
        run: whoami

      - name: "working directory"
        run: |
          pwd
          ls -la
 
      - name: "checkout repo"
        uses: actions/checkout@v3

      - name: "current working directory after checkout"
        run: |
          pwd
          ls -la

      - name: "Terraform"
        run: |
          wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
          unzip terraform_1.6.6_linux_amd64.zip
          ./terraform version
          ls -la
 
      - name: "Version script"
        run: |
          chmod +x script.sh
          ./script.sh
