---
name: "workflow"

on:
  push:
    branches:
      - master
      - branch1

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
  
      - name: "Date"
        run: date
        
      - name: "OS"
        run : cat /etc/issue

      - name: "user"
        run: whoami

      - name: "working directory"
        run: |
          pwd
          ls -la
 
      - name: "checkout repo"
        uses: actions/checkout@v3

      - name: "current working directory after checkout"
        run: |
          pwd
          ls -la

      - name: "Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6" 

      - name: "Version script"
         run: |
           chmod +x script.sh
           ./script.sh
